name: Lint&Test

on:
  pull_request:
  push:
    branches:
      - master
      - dev

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install main deps
        run: yarn
      - name: Initialize
        run: yarn lerna bootstrap

  eslint:
    needs: setup
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: yarn lint

  test:
    needs: setup
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: yarn test
