name: Lint

on:
  push:
    branches:
      - dev

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install main deps
        run: yarn
      - name: Initialize
        run: yarn lerna bootstrap
      - name: Lint
        run: yarn lint
